version: 2
jobs:
   build:
     docker:
       - image: microsoft/aspnetcore-build
     steps:
       - checkout
       - run: dotnet restore ./src/Web.csproj
       - run: dotnet build ./src/Web.csproj